export type {
    BaseBridgeMessage,
    SessionConfig,
    AgentMode,
    PermissionLevel,
    RuntimeMode,
    SessionStatePayload,
    UserInputRequestPayload,
    PlanExitRequestPayload,
    SessionMessageAttachment,
    SessionMessageInput,
    ToolArguments,
    SessionContext,
    WorkspaceTreeNode,
    GitFileChange,
    GitCommitSummary,
    WorkspaceOperation,
    SessionInfo,
    WorkspaceTreeRequestMessage,
    WorkspaceTreeMessage,
    WorkspaceGitSummaryRequestMessage,
    WorkspaceGitSummaryMessage,
    WorkspaceOperationRequestMessage,
    WorkspaceOperationResultPayload,
    WorkspacePullResultMessage,
    WorkspacePushResultMessage,
    SessionHistoryItem,
    PermissionKind,
    PermissionRequestPayload,
    PermissionResponsePayload,
    ModelInfo,
    ModelPolicyState,
    ReasoningEffortLevel,
    HostSessionCapabilities,
    BridgeSettings,
    CapabilitiesStatePayload,
    ConnectionStatusPayload,
    ErrorPayload,
    QRPayload,
    ServerMessage,
    ClientMessage,
    PairingSuccessMessage,
    SessionCreatedMessage,
    SessionResumedMessage,
    SessionIdleMessage,
    SessionListMessage,
    SessionHistoryMessage,
    AssistantMessageMessage,
    AssistantMessageDeltaMessage,
    AssistantReasoningMessage,
    AssistantReasoningDeltaMessage,
    ToolExecutionStartMessage,
    ToolExecutionPartialResultMessage,
    ToolExecutionProgressMessage,
    ToolExecutionCompleteMessage,
    PermissionRequestMessage,
    UserInputRequestMessage,
    ModelsListMessage,
    ErrorMessage,
    ConnectionStatusMessage,
    TokenRefreshMessage,
    ReconnectReadyMessage,
    CapabilitiesStateMessage,
    SessionStateMessage,
    SessionErrorMessage,
    SessionTitleChangedMessage,
    AssistantIntentMessage,
    PlanExitRequestMessage,
    AuthPairMessage,
    SessionCreateMessage,
    SessionResumeMessage,
    SessionListRequestMessage,
    SessionDeleteMessage,
    MessageSendMessage,
    MessageAbortMessage,
    PermissionRespondMessage,
    UserInputRespondMessage,
    SettingsUpdateMessage,
    SessionModeUpdateMessage,
    PermissionLevelUpdateMessage,
    ModelsRequestMessage,
    ReconnectMessage,
    CapabilitiesRequestMessage,
} from "./protocol";

export type {
    AdaptedPermissionRequest,
    AdaptedToolStartDetails,
    AdaptedUserInputRequest,
    AdaptedSessionState,
    AdaptedPlanExitRequest,
    AdaptedCopilotSession,
    AdaptedCopilotClient,
} from "./adapter";

export {
    serverMessageSchema,
    clientMessageSchema,
    qrPayloadSchema,
} from "./schemas";

export {
    BridgeError,
    WebSocketError,
    AuthError,
    PermissionDeniedError,
    PermissionTimeoutError,
    SDKError,
    RateLimitError,
    ReplayAttackError,
} from "./errors";

export {
    DEFAULT_WS_PORT,
    PAIRING_TOKEN_BYTES,
    PAIRING_TOKEN_TTL_MS,
    JWT_TTL_SECONDS,
    JWT_REFRESH_THRESHOLD_MS,
    JWT_SECRET_ROTATION_MS,
    JWT_SECRET_GRACE_MS,
    HEARTBEAT_INTERVAL_MS,
    PERMISSION_TIMEOUT_MS,
    MAX_SESSIONS,
    MAX_MESSAGE_BUFFER,
    REPLAY_WINDOW_MS,
    RATE_LIMIT_PAIRING_MAX,
    RATE_LIMIT_PAIRING_WINDOW_MS,
    RATE_LIMIT_MESSAGE_MAX,
    RATE_LIMIT_MESSAGE_WINDOW_MS,
    CONFIG_DIR_NAME,
    CERT_FILENAME,
    KEY_FILENAME,
    JWT_SECRET_FILENAME,
    QR_PAYLOAD_VERSION,
    MODEL_UNKNOWN,
} from "./constants";
